### ISSUE TITLE
URL to video that is part of a playlist is recognized as a playlist

### ISSUE THREAD

**Issue by MrMcShroom** [itaisteinherz/is-playlist#1] opened 2018-05-17 20:16 UTC
Meaning that if I were to copy a video from youtube that was in the middle of a playlist it would return true.

**Comment by itaisteinherz** [comment] 2018-11-15 09:31
Sorry it has taken me so long to get back to you, for some reason I didn't get notified of this issue.

> if I were to copy a video from youtube that was in the middle of a playlist it would return true

That's the expected behavior, since `is-playlist` returns `true` if the given URL is either a playlist or a video that is part of a playlist (the video's index in the playlist doesn't matter, since the video is still a part of a playlist).

We could add an option to strictly check if the given URL is a playlist.

**Comment by aslafy-z** [comment] 2018-11-17 12:42
You might want to update the readme to reflect this :wink:

**Comment by itaisteinherz** [comment] 2018-11-17 14:46
I've documented this behavior in [`readme.md`](https://github.com/itaisteinherz/is-playlist#isplaylisturl).

**Comment by itaisteinherz** [comment] 2018-11-17 15:18
I've opened #2 to discuss adding an option that changes the current behavior to what @MrMcShroom originally expected.
I'm going to close this now as this isn't a bug, but a design choice.

**Closed as completed by itaisteinherz** 2018-11-17 15:18 UTC
